services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgres
      - DB_POSTGRES_HOST=${SUPABASE_HOST:-aws-1-us-east-2.pooler.supabase.com}
      - DB_POSTGRES_PORT=${SUPABASE_PORT:-6543}
      - DB_POSTGRES_DATABASE=${SUPABASE_DB:-postgres}
      - DB_POSTGRES_USER=${SUPABASE_USER:-postgres.pjgpqoqjufkhnsmeslcw}
      - DB_POSTGRES_PASSWORD=${SUPABASE_PASSWORD:-steven16082004.}
      - DB_POSTGRES_SCHEMA=public
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Guayaquil}
      - TZ=${TZ:-America/Guayaquil}
      - N8N_ENCRYPTION_KEY=my_local_key_123
      - N8N_RUNNERS_ENABLED=true
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data: