services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${SUPABASE_HOST:-aws-1-us-east-1.pooler.supabase.com}
      - DB_POSTGRESDB_PORT=${SUPABASE_PORT:-6543}
      - DB_POSTGRESDB_DATABASE=${SUPABASE_DB:-postgres}
      - DB_POSTGRESDB_USER=${SUPABASE_USER:-postgres.jovwozktuvlalbodxqzw}
      - DB_POSTGRESDB_PASSWORD=${SUPABASE_PASSWORD:-n8nsupabase}
      - DB_POSTGRESDB_SCHEMA=public
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Guayaquil}
      - TZ=${TZ:-America/Guayaquil}
      - N8N_ENCRYPTION_KEY=my_local_key_123
      - N8N_RUNNERS_ENABLED=true
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
